# ==================== 任务配置 ====================
task:
  name: sim_lifting_cube_scripted
  dataset_dir: ./data_sim_episodes/26032503_fairino5_single_config
  num_episodes: 50
  episode_len: 400
  camera_names:
    - top

# ==================== 设备配置 ====================
equipment:
  model: fairino5_single

# ==================== 渲染配置 ====================
render:
  onscreen_render: false